config/routes.rb
Rails.application.routes.draw do

  root 'paintings#index'
  resources :paintings
  resources :museums 

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :paintings
  has_many :museums, through: :paintings
end

app/models/museum.rb
class Museum < ActiveRecord::Base
  has_many :paintings
  has_many :artists, through: :paintings
  
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :museum
  belongs_to :artist


def self.search(query)
  where('title LIKE :query', :query => "%#{query}%")


end





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/museum_controller.rb
class MuseumController < ApplicationController


    def show
      @museum = Museum.find(params[:id])
    end



end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

  def index
    if params[:q]
      @paintings = Painting.search(params[:q])
    else
    @paintings = Painting.all
    end
  end

  def show
    def show
      @museum = Museum.find(params[:id])
    end

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/museum_helper.rb
module MuseumHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MuseumApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paintings/index.html.erb
<h1>Painting Gallery</h1>
<h3><%= link_to "+ Add New Painting", new_painting_path %></h3>
<%= form_tag "/", method: "GET" do %>
 <% text_field_tag :q %>
 <%= submit_tag "Search" %>
<%end %>

<br/><hr/>

<% if @paintings.any? %>
  <% @paintings.each do |painting| %>
    <section>
      <h3><strong>Title</strong>: <%= link_to painting.title, painting %></h3>
      <%= image_tag painting.image %>
      <p><strong>Year</strong>: <%= painting.year %></p>
      <p><strong>Style</strong>: <%= painting.style %></p>
      <p><strong>Museum</strong>: <%= link_to painting.museum.name, painting.museum %></p>
    </section>
    <hr>
  <% end %>
<% else %>
  <h4>Sorry, no paintings matched your query.</h4>
<% end %>

app/views/paintings/show.html.erb
<h1><%= @museum.name %></h1>
<p><%= @museum.city %></p>

<hr>

<% @museum.paintings.each do |painting| %>
  <section>
    <h3><strong>Title</strong>: <%= link_to painting.title, painting %></h3>
    <%= image_tag painting.image %>
    <p><strong>Year</strong>: <%= painting.year %></p>
    <p><strong>Style</strong>: <%= painting.style %></p>
    <hr>
  </section>
<% end %>

<p><%= link_to "Edit Museum", edit_museum_path(@museum) %></p>